[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "python311Packages.cython", "python311Packages.setuptools"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "bash start.sh"
